const mockData = [
  {
    treeId: 77,
    type: 10,
    name: "javascript",
    parentTreeId: null,
    childrenTree: [
      {
        treeId: 88,
        type: 20,
        name: "Array",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 653,
        type: 20,
        name: "정규식",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 87,
        type: 20,
        name: "Object",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 78,
        type: 20,
        name: "change element id and name",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 79,
        type: 20,
        name: "window.onload",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 80,
        type: 20,
        name: "window.location.reload()",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 81,
        type: 20,
        name: "async vs defer",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 82,
        type: 20,
        name: "use strict",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 83,
        type: 20,
        name: "data types: primative",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 84,
        type: 20,
        name: "Operator",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 85,
        type: 20,
        name: "Function",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 86,
        type: 20,
        name: "Class",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 89,
        type: 20,
        name: "JSON",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 90,
        type: 20,
        name: "Promise",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 91,
        type: 20,
        name: "aync & await",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 95,
        type: 20,
        name: "key event",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 317,
        type: 20,
        name: "문자열 특정문자 갯수 찾기",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 383,
        type: 20,
        name: "Optional chaining",
        parentTreeId: 77,
        childrenTree: null,
      },
      {
        treeId: 1212,
        type: 20,
        name: "changeCommaToHash",
        parentTreeId: 77,
        childrenTree: null,
      },
    ],
  },
  {
    treeId: 484,
    type: 10,
    name: "파이썬",
    parentTreeId: null,
    childrenTree: [
      {
        treeId: 496,
        type: 10,
        name: "Sequence Types",
        parentTreeId: 484,
        childrenTree: [
          {
            treeId: 487,
            type: 20,
            name: "\bSequence",
            parentTreeId: 496,
            childrenTree: null,
          },
          {
            treeId: 493,
            type: 20,
            name: "List",
            parentTreeId: 496,
            childrenTree: null,
          },
          {
            treeId: 494,
            type: 20,
            name: "Tuple",
            parentTreeId: 496,
            childrenTree: null,
          },
          {
            treeId: 495,
            type: 20,
            name: "Range",
            parentTreeId: 496,
            childrenTree: null,
          },
        ],
      },
      {
        treeId: 497,
        type: 10,
        name: "Text Sequence Type",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 501,
        type: 10,
        name: "Set Types",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 555,
        type: 10,
        name: "Mapping Types",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 575,
        type: 10,
        name: "Django",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 577,
        type: 10,
        name: "Django REST framework",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 485,
        type: 20,
        name: "파이썬이란",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 486,
        type: 20,
        name: "기본 문법",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 488,
        type: 20,
        name: "data type",
        parentTreeId: 484,
        childrenTree: null,
      },
      {
        treeId: 574,
        type: 20,
        name: "pip",
        parentTreeId: 484,
        childrenTree: null,
      },
    ],
  },
  {
    treeId: 375,
    type: 10,
    name: "mysql",
    parentTreeId: null,
    childrenTree: [
      {
        treeId: 582,
        type: 10,
        name: "응용",
        parentTreeId: 375,
        childrenTree: null,
      },
      {
        treeId: 671,
        type: 10,
        name: "인덱스",
        parentTreeId: 375,
        childrenTree: null,
      },
      {
        treeId: 679,
        type: 10,
        name: "내장 함수",
        parentTreeId: 375,
        childrenTree: null,
      },
      {
        treeId: 1093,
        type: 10,
        name: "실행계획",
        parentTreeId: 375,
        childrenTree: null,
      },
      {
        treeId: 680,
        type: 10,
        name: "정리",
        parentTreeId: 375,
        childrenTree: null,
      },
      {
        treeId: 1105,
        type: 10,
        name: "구문분석",
        parentTreeId: 375,
        childrenTree: [
          {
            treeId: 1125,
            type: 10,
            name: "CREATE",
            parentTreeId: 1105,
            childrenTree: null,
          },
          {
            treeId: 1126,
            type: 10,
            name: "Compound Statement",
            parentTreeId: 1105,
            childrenTree: [
              {
                treeId: 1130,
                type: 10,
                name: "Flow Control Statements",
                parentTreeId: 1126,
                childrenTree: [
                  {
                    treeId: 1131,
                    type: 20,
                    name: "CASE",
                    parentTreeId: 1130,
                    childrenTree: null,
                  },
                  {
                    treeId: 1132,
                    type: 20,
                    name: "IF",
                    parentTreeId: 1130,
                    childrenTree: null,
                  },
                  {
                    treeId: 1133,
                    type: 20,
                    name: "LOOP",
                    parentTreeId: 1130,
                    childrenTree: null,
                  },
                  {
                    treeId: 1134,
                    type: 20,
                    name: "REPEAT",
                    parentTreeId: 1130,
                    childrenTree: null,
                  },
                  {
                    treeId: 1135,
                    type: 20,
                    name: "WHILE",
                    parentTreeId: 1130,
                    childrenTree: null,
                  },
                ],
              },
              {
                treeId: 1138,
                type: 10,
                name: "Condition Handling",
                parentTreeId: 1126,
                childrenTree: null,
              },
              {
                treeId: 1127,
                type: 20,
                name: "BEGIN ... END",
                parentTreeId: 1126,
                childrenTree: null,
              },
              {
                treeId: 1128,
                type: 20,
                name: "Statement Labels",
                parentTreeId: 1126,
                childrenTree: null,
              },
              {
                treeId: 1129,
                type: 20,
                name: "DECLARE",
                parentTreeId: 1126,
                childrenTree: null,
              },
              {
                treeId: 1136,
                type: 20,
                name: "CURSOR",
                parentTreeId: 1126,
                childrenTree: null,
              },
            ],
          },
          {
            treeId: 1227,
            type: 10,
            name: "Transactional and Locking Statements",
            parentTreeId: 1105,
            childrenTree: null,
          },
        ],
      },
    ],
  },
  {
    treeId: 218,
    type: 10,
    name: "AWS",
    parentTreeId: null,
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 1141,
    type: 10,
    name: "TanStack Query",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 1191,
    type: 10,
    name: "terraform",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 187,
    type: 10,
    name: "react",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 96,
    type: 10,
    name: "typescript",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 436,
    type: 10,
    name: "git",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 92,
    type: 10,
    name: "java",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 117,
    type: 10,
    name: "next",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 206,
    type: 10,
    name: "React DnD",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 182,
    type: 20,
    name: "용어",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 129,
    type: 20,
    name: "PHP",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 133,
    type: 20,
    name: "Cypress",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 134,
    type: 20,
    name: "node.js",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 135,
    type: 20,
    name: "inversify + typescript",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 215,
    type: 20,
    name: "Redux",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 216,
    type: 20,
    name: "Firebase",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 217,
    type: 20,
    name: "netlify",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 406,
    type: 20,
    name: "SWC",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 409,
    type: 20,
    name: "Webpack",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 441,
    type: 20,
    name: "쿠키/세션/토큰",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 554,
    type: 20,
    name: "docker",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 579,
    type: 20,
    name: "zsh",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 1090,
    type: 20,
    name: "NVM",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 1109,
    type: 20,
    name: "story book",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 479,
    type: 20,
    name: "Go란",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 483,
    type: 20,
    name: "oAuth란",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 475,
    type: 20,
    name: "스벨트란",
    parentTreeId: null,
    childrenTree: null,
  },
  {
    treeId: 477,
    type: 20,
    name: "Flutter란",
    parentTreeId: null,
    childrenTree: null,
  },
];

module.exports = mockData;
