const mockData = [
  {
    id: 77,
    type: 10,
    name: "javascript",
    children: [
      {
        id: 88,
        type: 20,
        name: "Array",
        parent: 77,
        children: null,
      },
      {
        id: 653,
        type: 20,
        name: "정규식",
        parent: 77,
        children: null,
      },
      {
        id: 87,
        type: 20,
        name: "Object",
        parent: 77,
        children: null,
      },
      {
        id: 78,
        type: 20,
        name: "change element id and name",
        parent: 77,
        children: null,
      },
      {
        id: 79,
        type: 20,
        name: "window.onload",
        parent: 77,
        children: null,
      },
      {
        id: 80,
        type: 20,
        name: "window.location.reload()",
        parent: 77,
        children: null,
      },
      {
        id: 81,
        type: 20,
        name: "async vs defer",
        parent: 77,
        children: null,
      },
      {
        id: 82,
        type: 20,
        name: "use strict",
        parent: 77,
        children: null,
      },
      {
        id: 83,
        type: 20,
        name: "data types: primative",
        parent: 77,
        children: null,
      },
      {
        id: 84,
        type: 20,
        name: "Operator",
        parent: 77,
        children: null,
      },
      {
        id: 85,
        type: 20,
        name: "Function",
        parent: 77,
        children: null,
      },
      {
        id: 86,
        type: 20,
        name: "Class",
        parent: 77,
        children: null,
      },
      {
        id: 89,
        type: 20,
        name: "JSON",
        parent: 77,
        children: null,
      },
      {
        id: 90,
        type: 20,
        name: "Promise",
        parent: 77,
        children: null,
      },
      {
        id: 91,
        type: 20,
        name: "aync & await",
        parent: 77,
        children: null,
      },
      {
        id: 95,
        type: 20,
        name: "key event",
        parent: 77,
        children: null,
      },
      {
        id: 317,
        type: 20,
        name: "문자열 특정문자 갯수 찾기",
        parent: 77,
        children: null,
      },
      {
        id: 383,
        type: 20,
        name: "Optional chaining",
        parent: 77,
        children: null,
      },
      {
        id: 1212,
        type: 20,
        name: "changeCommaToHash",
        parent: 77,
        children: null,
      },
    ],
  },
  {
    id: 484,
    type: 10,
    name: "파이썬",
    children: [
      {
        id: 496,
        type: 10,
        name: "Sequence Types",
        parent: 484,
        children: [
          {
            id: 487,
            type: 20,
            name: "\bSequence",
            parent: 496,
            children: null,
          },
          {
            id: 493,
            type: 20,
            name: "List",
            parent: 496,
            children: null,
          },
          {
            id: 494,
            type: 20,
            name: "Tuple",
            parent: 496,
            children: null,
          },
          {
            id: 495,
            type: 20,
            name: "Range",
            parent: 496,
            children: null,
          },
        ],
      },
      {
        id: 497,
        type: 10,
        name: "Text Sequence Type",
        parent: 484,
        children: null,
      },
      {
        id: 501,
        type: 10,
        name: "Set Types",
        parent: 484,
        children: null,
      },
      {
        id: 555,
        type: 10,
        name: "Mapping Types",
        parent: 484,
        children: null,
      },
      {
        id: 575,
        type: 10,
        name: "Django",
        parent: 484,
        children: null,
      },
      {
        id: 577,
        type: 10,
        name: "Django REST framework",
        parent: 484,
        children: null,
      },
      {
        id: 485,
        type: 20,
        name: "파이썬이란",
        parent: 484,
        children: null,
      },
      {
        id: 486,
        type: 20,
        name: "기본 문법",
        parent: 484,
        children: null,
      },
      {
        id: 488,
        type: 20,
        name: "data type",
        parent: 484,
        children: null,
      },
      {
        id: 574,
        type: 20,
        name: "pip",
        parent: 484,
        children: null,
      },
    ],
  },
  {
    id: 375,
    type: 10,
    name: "mysql",
    children: [
      {
        id: 582,
        type: 10,
        name: "응용",
        parent: 375,
        children: null,
      },
      {
        id: 671,
        type: 10,
        name: "인덱스",
        parent: 375,
        children: null,
      },
      {
        id: 679,
        type: 10,
        name: "내장 함수",
        parent: 375,
        children: null,
      },
      {
        id: 1093,
        type: 10,
        name: "실행계획",
        parent: 375,
        children: null,
      },
      {
        id: 680,
        type: 10,
        name: "정리",
        parent: 375,
        children: null,
      },
      {
        id: 1105,
        type: 10,
        name: "구문분석",
        parent: 375,
        children: [
          {
            id: 1125,
            type: 10,
            name: "CREATE",
            parent: 1105,
            children: null,
          },
          {
            id: 1126,
            type: 10,
            name: "Compound Statement",
            parent: 1105,
            children: [
              {
                id: 1130,
                type: 10,
                name: "Flow Control Statements",
                parent: 1126,
                children: [
                  {
                    id: 1131,
                    type: 20,
                    name: "CASE",
                    parent: 1130,
                    children: null,
                  },
                  {
                    id: 1132,
                    type: 20,
                    name: "IF",
                    parent: 1130,
                    children: null,
                  },
                  {
                    id: 1133,
                    type: 20,
                    name: "LOOP",
                    parent: 1130,
                    children: null,
                  },
                  {
                    id: 1134,
                    type: 20,
                    name: "REPEAT",
                    parent: 1130,
                    children: null,
                  },
                  {
                    id: 1135,
                    type: 20,
                    name: "WHILE",
                    parent: 1130,
                    children: null,
                  },
                ],
              },
              {
                id: 1138,
                type: 10,
                name: "Condition Handling",
                parent: 1126,
                children: null,
              },
              {
                id: 1127,
                type: 20,
                name: "BEGIN ... END",
                parent: 1126,
                children: null,
              },
              {
                id: 1128,
                type: 20,
                name: "Statement Labels",
                parent: 1126,
                children: null,
              },
              {
                id: 1129,
                type: 20,
                name: "DECLARE",
                parent: 1126,
                children: null,
              },
              {
                id: 1136,
                type: 20,
                name: "CURSOR",
                parent: 1126,
                children: null,
              },
            ],
          },
          {
            id: 1227,
            type: 10,
            name: "Transactional and Locking Statements",
            parent: 1105,
            children: null,
          },
        ],
      },
    ],
  },
  {
    id: 218,
    type: 10,
    name: "AWS",
    children: null,
  },
  {
    id: 1141,
    type: 10,
    name: "TanStack Query",
    children: null,
  },
  {
    id: 1191,
    type: 10,
    name: "terraform",
    children: null,
  },
  {
    id: 187,
    type: 10,
    name: "react",
    children: null,
  },
  {
    id: 96,
    type: 10,
    name: "typescript",
    children: null,
  },
  {
    id: 436,
    type: 10,
    name: "git",
    children: null,
  },
  {
    id: 92,
    type: 10,
    name: "java",
    children: null,
  },
  {
    id: 117,
    type: 10,
    name: "next",
    children: null,
  },
  {
    id: 206,
    type: 10,
    name: "React DnD",
    children: null,
  },
  {
    id: 182,
    type: 20,
    name: "용어",
    children: null,
  },
  {
    id: 129,
    type: 20,
    name: "PHP",
    children: null,
  },
  {
    id: 133,
    type: 20,
    name: "Cypress",
    children: null,
  },
  {
    id: 134,
    type: 20,
    name: "node.js",
    children: null,
  },
  {
    id: 135,
    type: 20,
    name: "inversify + typescript",
    children: null,
  },
  {
    id: 215,
    type: 20,
    name: "Redux",
    children: null,
  },
  {
    id: 216,
    type: 20,
    name: "Firebase",
    children: null,
  },
  {
    id: 217,
    type: 20,
    name: "netlify",
    children: null,
  },
  {
    id: 406,
    type: 20,
    name: "SWC",
    children: null,
  },
  {
    id: 409,
    type: 20,
    name: "Webpack",
    children: null,
  },
  {
    id: 441,
    type: 20,
    name: "쿠키/세션/토큰",
    children: null,
  },
  {
    id: 554,
    type: 20,
    name: "docker",
    children: null,
  },
  {
    id: 579,
    type: 20,
    name: "zsh",
    children: null,
  },
  {
    id: 1090,
    type: 20,
    name: "NVM",
    children: null,
  },
  {
    id: 1109,
    type: 20,
    name: "story book",
    children: null,
  },
  {
    id: 479,
    type: 20,
    name: "Go란",
    children: null,
  },
  {
    id: 483,
    type: 20,
    name: "oAuth란",
    children: null,
  },
  {
    id: 475,
    type: 20,
    name: "스벨트란",
    children: null,
  },
  {
    id: 477,
    type: 20,
    name: "Flutter란",
    children: null,
  },
];

module.exports = mockData;